# Generated by Django 4.2.21 on 2026-05-06 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PublicSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seller_name', models.CharField(default='CyphX Immobilier', max_length=255)),
                ('whatsapp_phone', models.CharField(default='+212600000000', help_text='International format, e.g. +212600000000', max_length=30)),
                ('default_language', models.CharField(choices=[('fr', 'Français'), ('ar', 'العربية')], default='fr', max_length=5)),
                ('supported_languages', models.JSONField(default=list, help_text='JSON array e.g. ["fr", "ar"]')),
                ('future_languages', models.JSONField(default=list, help_text='Planned languages e.g. ["es"]')),
            ],
            options={
                'verbose_name': 'Public Settings',
                'verbose_name_plural': 'Public Settings',
            },
        ),
    ]
