# Generated by Django 4.2.21 on 2026-05-07 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('leads', '0001_initial'),
        ('properties', '0001_initial'),
        ('interactions', '0001_initial'),
        ('crm', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='interaction',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='leads.lead'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='opportunity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='crm.opportunity'),
        ),
        migrations.AddField(
            model_name='interaction',
            name='property',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to='properties.property'),
        ),
    ]
